In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
datasets= pd.read_csv('/content/sample_data/Real estate.csv')

In [4]:
datasets

No  X1 transaction date  ...  X6 longitude  Y house price of unit area
0      1             2012.917  ...     121.54024                        37.9
1      2             2012.917  ...     121.53951                        42.2
2      3             2013.583  ...     121.54391                        47.3
3      4             2013.500  ...     121.54391                        54.8
4      5             2012.833  ...     121.54245                        43.1
..   ...                  ...  ...           ...                         ...
409  410             2013.000  ...     121.50381                        15.4
410  411             2012.667  ...     121.54310                        50.0
411  412             2013.250  ...     121.53986                        40.6
412  413             2013.000  ...     121.54067                        52.5
413  414             2013.500  ...     121.54310                        63.9

[414 rows x 8 columns]

In [5]:
X= datasets.iloc[:,1:7].values
X

array([[2012.917  ,   32.     ,   84.87882,   10.     ,   24.98298,
         121.54024],
       [2012.917  ,   19.5    ,  306.5947 ,    9.     ,   24.98034,
         121.53951],
       [2013.583  ,   13.3    ,  561.9845 ,    5.     ,   24.98746,
         121.54391],
       ...,
       [2013.25   ,   18.8    ,  390.9696 ,    7.     ,   24.97923,
         121.53986],
       [2013.     ,    8.1    ,  104.8101 ,    5.     ,   24.96674,
         121.54067],
       [2013.5    ,    6.5    ,   90.45606,    9.     ,   24.97433,
         121.5431 ]])

In [9]:
y=datasets.iloc[:,-1].values
y

array([ 37.9,  42.2,  47.3,  54.8,  43.1,  32.1,  40.3,  46.7,  18.8,
        22.1,  41.4,  58.1,  39.3,  23.8,  34.3,  50.5,  70.1,  37.4,
        42.3,  47.7,  29.3,  51.6,  24.6,  47.9,  38.8,  27. ,  56.2,
        33.6,  47. ,  57.1,  22.1,  25. ,  34.2,  49.3,  55.1,  27.3,
        22.9,  25.3,  47.7,  46.2,  15.9,  18.2,  34.7,  34.1,  53.9,
        38.3,  42. ,  61.5,  13.4,  13.2,  44.2,  20.7,  27. ,  38.9,
        51.7,  13.7,  41.9,  53.5,  22.6,  42.4,  21.3,  63.2,  27.7,
        55. ,  25.3,  44.3,  50.7,  56.8,  36.2,  42. ,  59. ,  40.8,
        36.3,  20. ,  54.4,  29.5,  36.8,  25.6,  29.8,  26.5,  40.3,
        36.8,  48.1,  17.7,  43.7,  50.8,  27. ,  18.3,  48. ,  25.3,
        45.4,  43.2,  21.8,  16.1,  41. ,  51.8,  59.5,  34.6,  51. ,
        62.2,  38.2,  32.9,  54.4,  45.7,  30.5,  71. ,  47.1,  26.6,
        34.1,  28.4,  51.6,  39.4,  23.1,   7.6,  53.3,  46.4,  12.2,
        13. ,  30.6,  59.6,  31.3,  48. ,  32.5,  45.5,  57.4,  48.6,
        62.9,  55. ,

In [10]:
X=X.reshape(414,6)
X

array([[2012.917  ,   32.     ,   84.87882,   10.     ,   24.98298,
         121.54024],
       [2012.917  ,   19.5    ,  306.5947 ,    9.     ,   24.98034,
         121.53951],
       [2013.583  ,   13.3    ,  561.9845 ,    5.     ,   24.98746,
         121.54391],
       ...,
       [2013.25   ,   18.8    ,  390.9696 ,    7.     ,   24.97923,
         121.53986],
       [2013.     ,    8.1    ,  104.8101 ,    5.     ,   24.96674,
         121.54067],
       [2013.5    ,    6.5    ,   90.45606,    9.     ,   24.97433,
         121.5431 ]])

In [11]:
y=y.reshape(414,)
y

array([ 37.9,  42.2,  47.3,  54.8,  43.1,  32.1,  40.3,  46.7,  18.8,
        22.1,  41.4,  58.1,  39.3,  23.8,  34.3,  50.5,  70.1,  37.4,
        42.3,  47.7,  29.3,  51.6,  24.6,  47.9,  38.8,  27. ,  56.2,
        33.6,  47. ,  57.1,  22.1,  25. ,  34.2,  49.3,  55.1,  27.3,
        22.9,  25.3,  47.7,  46.2,  15.9,  18.2,  34.7,  34.1,  53.9,
        38.3,  42. ,  61.5,  13.4,  13.2,  44.2,  20.7,  27. ,  38.9,
        51.7,  13.7,  41.9,  53.5,  22.6,  42.4,  21.3,  63.2,  27.7,
        55. ,  25.3,  44.3,  50.7,  56.8,  36.2,  42. ,  59. ,  40.8,
        36.3,  20. ,  54.4,  29.5,  36.8,  25.6,  29.8,  26.5,  40.3,
        36.8,  48.1,  17.7,  43.7,  50.8,  27. ,  18.3,  48. ,  25.3,
        45.4,  43.2,  21.8,  16.1,  41. ,  51.8,  59.5,  34.6,  51. ,
        62.2,  38.2,  32.9,  54.4,  45.7,  30.5,  71. ,  47.1,  26.6,
        34.1,  28.4,  51.6,  39.4,  23.1,   7.6,  53.3,  46.4,  12.2,
        13. ,  30.6,  59.6,  31.3,  48. ,  32.5,  45.5,  57.4,  48.6,
        62.9,  55. ,

In [63]:
#from sklearn.compose import ColumnTransformer
#from sklearn.preprocessing import OneHotEncoder

In [64]:
#encoder =  OneHotEncoder()

#ct = ColumnTransformer(transformers=[('encoder',encoder, [3])], remainder='passthrough')

In [65]:
#X = ct.fit_transform(X)

In [66]:
#X

Splitting the dataset

In [67]:
from sklearn.model_selection import train_test_split

In [68]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state= 25)

In [69]:
print(X_train)

  (0, 48)	1.0
  (0, 232)	1.0
  (0, 234)	1.0
  (0, 238)	1.0
  (0, 245)	2013.5
  (0, 246)	25.3
  (0, 247)	1583.722
  (0, 248)	24.96622
  (1, 181)	1.0
  (1, 232)	1.0
  (1, 234)	1.0
  (1, 243)	1.0
  (1, 245)	2013.5
  (1, 246)	6.5
  (1, 247)	90.45606
  (1, 248)	24.97433
  (2, 12)	1.0
  (2, 232)	1.0
  (2, 234)	1.0
  (2, 236)	1.0
  (2, 245)	2012.75
  (2, 246)	16.1
  (2, 247)	4066.587
  (2, 248)	24.94297
  (3, 99)	1.0
  :	:
  (368, 248)	24.97795
  (369, 108)	1.0
  (369, 232)	1.0
  (369, 234)	1.0
  (369, 240)	1.0
  (369, 245)	2013.5
  (369, 246)	13.6
  (369, 247)	492.2313
  (369, 248)	24.96515
  (370, 112)	1.0
  (370, 232)	1.0
  (370, 234)	1.0
  (370, 244)	1.0
  (370, 245)	2013.333
  (370, 246)	7.1
  (370, 247)	379.5575
  (370, 248)	24.98343
  (371, 123)	1.0
  (371, 232)	1.0
  (371, 234)	1.0
  (371, 240)	1.0
  (371, 245)	2013.167
  (371, 246)	26.6
  (371, 247)	482.7581
  (371, 248)	24.97433


In [70]:
print(y_train)

[ 30.6  63.9  12.9  40.3  30.5  35.1  48.2  59.5  46.6  39.7  46.1  46.6
  42.5  30.5  23.5  32.4  20.   37.7  54.4  29.3  36.3  37.4  31.9  78.
  38.6  31.1  11.6  56.3  38.3  33.1  48.   36.5  52.5  45.1  38.8  25.6
  42.7  59.6  13.4  46.1  44.3  34.6  48.2  31.7  47.7  25.5  47.3  42.1
  39.6  25.7  29.5  67.7  28.5  39.3  62.9  41.9  30.7  15.6  25.3  25.6
  41.4  37.2  51.8  28.5  46.4  48.5  54.4  26.5  39.7  55.   41.6  17.4
  40.6  40.6  27.7  42.2  50.4  38.1   7.6  42.3  22.1  49.7  43.1  39.
  34.1  38.5  27.3  21.4  29.3  21.8  40.9  51.4  41.5  38.1  15.4  25.
  58.   61.9  27.   36.6  52.2  31.3  36.7  11.2  22.6  25.7  56.2  29.8
  31.3  34.1  37.3  20.5  42.3  37.4  42.8  12.8  23.7  41.   17.7  53.3
  23.8  43.2  35.6  43.1  15.9  24.7  28.1  28.6  15.5  45.5  63.3  53.5
  50.7  57.4  55.3  29.3  51.6  39.5  39.7  71.   36.8  53.3  42.6  42.2
  52.7  33.1  33.4  70.1  36.5  52.2  42.   39.6  40.   21.3  55.   59.
  31.3  51.   22.1  44.3  18.3  54.8  40.8  36.3  42.  

In [73]:
print(X_test)

  (0, 219)	1.0
  (0, 232)	1.0
  (0, 234)	1.0
  (0, 237)	1.0
  (0, 245)	2013.0
  (0, 246)	13.0
  (0, 247)	750.0704
  (0, 248)	24.97371
  (1, 152)	1.0
  (1, 232)	1.0
  (1, 235)	1.0
  (1, 245)	2013.25
  (1, 246)	1.1
  (1, 247)	193.5845
  (1, 248)	24.96571
  (2, 201)	1.0
  (2, 232)	1.0
  (2, 234)	1.0
  (2, 241)	1.0
  (2, 245)	2013.083
  (2, 246)	10.1
  (2, 247)	279.1726
  (2, 248)	24.97528
  (3, 137)	1.0
  (3, 232)	1.0
  :	:
  (38, 248)	24.94155
  (39, 121)	1.0
  (39, 232)	1.0
  (39, 234)	1.0
  (39, 239)	1.0
  (39, 245)	2012.917
  (39, 246)	21.2
  (39, 247)	512.5487
  (39, 248)	24.974
  (40, 110)	1.0
  (40, 232)	1.0
  (40, 234)	1.0
  (40, 242)	1.0
  (40, 245)	2013.333
  (40, 246)	3.9
  (40, 247)	49.66105
  (40, 248)	24.95836
  (41, 27)	1.0
  (41, 232)	1.0
  (41, 234)	1.0
  (41, 238)	1.0
  (41, 245)	2013.083
  (41, 246)	7.6
  (41, 247)	2175.03
  (41, 248)	24.96305


In [74]:
print(len(X_test))
print(len(X_train))

TypeError: ignored

In [46]:
print(y_test)

[37.  49.  47.9 40.6 41.  24.7 43.7 45.4 46.2 48.6 19.2 34.6 42.2 55.
 47.  47.7 40.9 13.  39.4 23.1 23.9 38.2 55.2 37.4 62.1 63.2 36.2 23.1
 14.7 55.5 19.2 23.5 26.6 27.3 35.5 49.3 24.7 18.6 16.7 42.5 56.8 27.7]


In [47]:
print(len(y_test))
print(len(y_train))
X_train.shape


42
372


(372, 18)

Model Setup

In [48]:
from sklearn.linear_model import LinearRegression

In [49]:
model = LinearRegression()

Training

In [50]:
model.fit(X_train, y_train)

LinearRegression()

Predicting

In [51]:
y_pred = model.predict(X_test)

In [52]:
[y_test, y_pred]

[array([37. , 49. , 47.9, 40.6, 41. , 24.7, 43.7, 45.4, 46.2, 48.6, 19.2,
        34.6, 42.2, 55. , 47. , 47.7, 40.9, 13. , 39.4, 23.1, 23.9, 38.2,
        55.2, 37.4, 62.1, 63.2, 36.2, 23.1, 14.7, 55.5, 19.2, 23.5, 26.6,
        27.3, 35.5, 49.3, 24.7, 18.6, 16.7, 42.5, 56.8, 27.7]),
 array([33.85655928, 50.24107373, 46.83641129, 46.8061034 , 35.98028768,
        27.52710627, 42.86993906, 50.02461517, 47.22112989, 49.75812428,
        14.31253102, 39.76385005, 37.52067992, 43.7564143 , 43.43704866,
        45.88774494, 45.00675329, 14.31253102, 45.27184271, 31.90723293,
        31.32384207, 42.98942929, 42.4565879 , 36.37715112, 47.21577965,
        52.98724866, 47.17113387, 29.19767289, 14.33176893, 47.63099154,
        15.14507925, 30.52797013, 27.98443452, 34.47290191, 42.37471946,
        49.46568998, 20.19155663, 12.88215801, 16.83009657, 36.11066976,
        48.21096636, 28.41873022])]

Evaluating Model

In [53]:
from sklearn.metrics import r2_score

In [54]:
r2_score(y_test, y_pred)

0.7919351440193901

In [56]:
X_test[0]

array([1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 2.0130000e+03, 1.3000000e+01, 7.5007040e+02,
       2.4973710e+01, 1.2154951e+02])

Predicting on single value

In [3]:
x1= ([[2012.917,32, 84.87, 10, 24.98, 121.54]])
y1 = model.predict(x1)

NameError: ignored